name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Set up test deps
      run: |
        git clone https://github.com/etclabscore/core-geth.git
        cd core-geth
        make geth
        echo "$(pwd)/build/bin" >> $GITHUB_PATH

    - name: Test
      run: go test -v ./...
